#RabbitMQ Configuration
spring:
  cloud:
    stream:
      source: eventPublisher
      bindings:
        eventPublisher-out-0:
          destination: sweng.events
          binder: cloud_rabbit
      binders:
        cloud_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: cow.rmq2.cloudamqp.com
                port: 5672
                username: ghkcurap
                password: 6a2CWs9YHE0cRhinwBdu2QRJaBXFiwmS
                virtual-host: ghkcurap
  #repeat the rabbitmq credentials as follows when actuator health checks are active:
  rabbitmq:
    host: cow.rmq2.cloudamqp.com
    port: 5672
    username: ghkcurap
    password: 6a2CWs9YHE0cRhinwBdu2QRJaBXFiwmS
    virtual-host: ghkcurap