#RabbitMQ Configuration
spring:
  cloud:
    stream:
      rabbit:
        bindings:
          eventConsumer-in-0:
            consumer:
              transacted: true
              max-attempts: 3
          eventPublisher-out-1:
            producer:
              transacted: true
          eventPublisher-out-2:
            producer:
              transacted: true
      binders:
        cloud_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq.team12.svc.cluster.local
                username: admin
                password: password
                virtual-host: /

  #repeat the rabbitmq credentials as follows when actuator health checks are active:
  rabbitmq:
    host: rabbitmq.team12.svc.cluster.local
    username: admin
    password: password
    virtual-host: /
