#RabbitMQ Configuration
spring:
  cloud:
    stream:
      bindings:
        eventConsumer-in-0:
          destination: sweng.events.registeredEvent
          binder: cloud_rabbit
        eventPublisher-out-1:
          destination: sweng.events.MealChangedEvent
          binder: cloud_rabbit
        eventPublisher-out-2:
          destination: sweng.events.MealAddedEvent
          binder: cloud_rabbit

      binders:
        cloud_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq.team12.svc.cluster.local
                username: admin
                password: password
                virtual-host: /

  #repeat the rabbitmq credentials as follows when actuator health checks are active:
  rabbitmq:
    host: rabbitmq.team12.svc.cluster.local
    username: admin
    password: password
    virtual-host: /
